language: node_js
node_js:
  - node
after_success:
  - yarn build
before_deploy:
  - cd ./lib
deploy:
  provider: heroku
  api_key:
    secure: XRwnQ4FpD9+ry1s8Z1ETv+SWSs6+6AOKJpGvsssQ4rfFcyp18kUV+TGKrxY/dQ32lE6al4jSt92CdAkgf8puQASRmyA5v/2mfSeBUfRvs+rSwsseEz8tL5+cYysujFndMrX3KBxCzbzOLCRtpC3c334D81SUShGxv5g5+IRdZjqB1/yLNMr4GZdovACmLqcWI8dxLjUZA9qRScwOm2kdnKNPzdGM9cJhbCIC3CTbZfNcXT1IH81s8LoaXytsBm8/P7MxZOxhV4b7k0Y/9ceyhna0aREd5oLt7L6mIdRGEjd1/achnNqM6+hQLkH1dsnOt79QS2mwucgJ49GrbtphdkdZC/qrE6M71Ap07rRL9dr0JbbimGo6YPZRuZX/+XHAWH28+qMeZ7TGcvwfw7rGxVZ7FONKkSkpGcoJF1PKOoXNjrjnp17ulvmvHo8WHx0qsQO5LIU93uRTaeDeVb9IaHWR4rpX0lZR9bdRmSIXOf2lhFFC8HZl5HB2ooNlXF9/GGoM3eKPn33m8nAgmdBAxDeE79tnspbOJ9RsK4rbDFbtCzJ1AK4Y85ZUEmMKBlGMBM3LnQP84RizSkngNf09Mj0lAMhVCPtnerxhnRX7sNJuCxe63hOXMAM6leIurs8vWQtDMyTsbrPOw8J+1aoSbhoYq7QqV2KLVOzJnMUa9Zc=
  app: simplecodemashschedule
  skip_cleanup: true
  on:
    repo: jgretz/simple-codemash-schedule
