language: node_js
node_js:
- '10'
after_success:
- yarn build
before_deploy:
- cd ./lib
deploy:
  provider: heroku
  api_key:
    secure: o3TndPq3d0JuqjsLFgdslxDm0WuzRCFtQ4ZsnbuGrfxnx8JtuPkRDLYuk3kS4K4mtKg+450jGyJ5tVYbdmcR7avJbx/OT8DqS+vqIOMoRWox3d74QYMZoDiLtFpSY9YxrfRlQ+QnfeCDj2rzQhUzHD9SmAqHeDnQ3nTOVo7q5fPA450sVM1VaxpsSNHWLwdC/ZbFv0PPHJAvCfD8IKbH31pwUIjPXavNPcFNJhp2VUVqSFAByOVs8j1hb3weSbymsTfh8bCwcpRLNouNiPfAcUkY7rhp3ogiLcdsJTl68hq0TUemzKxDD49z93iO7mGWQdZxiyU2CYNCWvcTTLDDJY5psjQeEAzKsMWW3Ir5erMXT2jbStGHAH7ibBviAl69dEmTW/muZAWQLupbhmWFo5n4rt+Po16QeXpdMn75eMgjYL+3oIunhEYODVJRCfJuAf/dPxVyZWySixSoDxYs1eih1ENgh4lBTk8xbUgN7KZtU55Zt8DUdlzteQ4VmBqw4IVjezqXZSm6p+yObRIrCERpnpjtsEQbLVkt7js0ER1NXOtzMUT1XzNGDoy9fYbOLiZlWFUHXaOuc0K8A9eIqhUWwcTNRRDdxzbimdG7xCUvDlMkd4kChejzr1UWvyNSbRus2nZ45mfncPnvsfXunHSWGPHmco4WexTb50AuIeo=
  app: altconfschedule
  skip_cleanup: true
  on:
    repo: jgretz/conference-schedule
